#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

VERSION="$(cat VERSION)"
PLUGIN_NAME="unraid-mcp"
PACKAGE_FILE="${PLUGIN_NAME}.tar"
BUILD_DIR="/tmp/${PLUGIN_NAME}-build"
INSTALL_DIR="${BUILD_DIR}/usr/local/emhttp/plugins/${PLUGIN_NAME}"
CONFIG_DIR="${BUILD_DIR}/boot/config/plugins/${PLUGIN_NAME}"

echo "==> Building Go binary..."
cd "$SCRIPT_DIR/go"
go build -o bin/unraid-mcp cmd/unraid-mcp/main.go
cd "$SCRIPT_DIR"

echo "==> Creating build directory..."
rm -rf "$BUILD_DIR"
mkdir -p "$INSTALL_DIR/bin"
mkdir -p "$INSTALL_DIR/scripts"
mkdir -p "$INSTALL_DIR/webgui"
mkdir -p "$INSTALL_DIR/memory"
mkdir -p "$CONFIG_DIR"

echo "==> Assembling package files..."
cp go/bin/unraid-mcp "$INSTALL_DIR/bin/unraid-mcp"
cp plugin/scripts/install.sh "$INSTALL_DIR/scripts/install.sh"
cp plugin/scripts/start.sh "$INSTALL_DIR/scripts/start.sh"
cp plugin/scripts/stop.sh "$INSTALL_DIR/scripts/stop.sh"
cp plugin/scripts/status.sh "$INSTALL_DIR/scripts/status.sh"
cp plugin/scripts/upgrade.sh "$INSTALL_DIR/scripts/upgrade.sh"
cp plugin/scripts/remove.sh "$INSTALL_DIR/scripts/remove.sh"
cp plugin/webgui/Settings.page "$INSTALL_DIR/webgui/Settings.page"
sed -i.bak "s/<version>[^<]*<\/version>/<version>${VERSION}<\/version>/" "$INSTALL_DIR/webgui/Settings.page" && rm -f "$INSTALL_DIR/webgui/Settings.page.bak"
cp memory/AGENT-SKILLS.md "$INSTALL_DIR/memory/AGENT-SKILLS.md"
cp memory/AGENT-MEMORY.md "$INSTALL_DIR/memory/AGENT-MEMORY.md"
cp plugin/unraid-mcp.plg "$INSTALL_DIR/unraid-mcp.plg"
chmod +x "$INSTALL_DIR/scripts/"*.sh

echo "==> Creating config.cfg..."
cat > "$CONFIG_DIR/config.cfg" << 'ENVEOF'
UNRAID_API_URL=""
UNRAID_API_KEY=""
TRANSPORT="stdio"
UNRAID_MCP_HOST="127.0.0.1"
UNRAID_MCP_PORT="6970"
READ_ONLY="true"
ALLOW_ARRAY_STOP="false"
ALLOW_ARRAY_START="false"
ALLOW_ARRAY_ADD_DISK="false"
ALLOW_ARRAY_REMOVE_DISK="false"
ALLOW_ARRAY_CLEAR_STATS="false"
ALLOW_CONTAINER_STOP="false"
ALLOW_CONTAINER_REMOVE="false"
ALLOW_CONTAINER_RESTART="false"
ALLOW_VM_FORCE_STOP="false"
ALLOW_VM_RESET="false"
ALLOW_VM_STOP="false"
ALLOW_PLUGIN_INSTALL="false"
ALLOW_PLUGIN_REMOVE="false"
ALLOW_SETTING_UPDATES="false"
ALLOW_SSH_UPDATE="false"
ALLOW_TIME_UPDATE="false"
ALLOW_NOTIFICATION_DELETE="false"
ALLOW_API_KEY_CREATE="false"
ALLOW_API_KEY_DELETE="false"
ALLOW_FLASH_BACKUP="false"
ALLOW_RCLONE_OPERATIONS="false"
ALLOW_CONNECT_ACTIONS="false"
ALLOW_ONBOARDING_ACTIONS="false"
ALLOW_DOCKER_ACTIONS="false"
ALLOW_VM_ACTIONS="false"
ALLOW_ARRAY_ACTIONS="false"
ALLOW_DESTRUCTIVE="false"
UNRAID_MCP_LOG_LEVEL="info"
UNRAID_VERIFY_SSL="true"
UNRAID_ALLOW_INSECURE_TLS="false"
UNRAID_MCP_BEARER_TOKEN=""
UNRAID_MCP_DISABLE_HTTP_AUTH="false"
ENVEOF
chmod 600 "$CONFIG_DIR/config.cfg"

echo "==> Creating package tarball..."
cd "$BUILD_DIR"
tar -cf "$SCRIPT_DIR/$PACKAGE_FILE" .
cd "$SCRIPT_DIR"

rm -rf "$BUILD_DIR"

echo "==> Done: $PACKAGE_FILE ($(du -h "$PACKAGE_FILE" | cut -f1))"
